### ISSUE TITLE
BUG: Hide the boxes if there is no todo's or completed task 

### ISSUE THREAD

**Issue by kantakshay** [kantakshay/CRUD-app#1]
![Screenshot (222)](https://github.com/kantakshay/CRUD-app/assets/84266746/7dd7772f-cda0-45d4-9f10-6e3885c904dd)

**Comment by TusharPani14** [comment]
"Hi Kantakshay, 
I am interested in working on this issue and would love to help out."

**Comment by kantakshay** [comment]
> "Hi Kantakshay, I am interested in working on this issue and would love to help out."

Thanks, @TusharPani14 for your valuable time

**Comment by TusharPani14** [comment]
The issue has been resolved, but several other issues remain like deleting a task from the doneTask section removes the entire div. Please specify the additional issues, and I'll be happy to contribute.
